#### 3. Fit the model & use it to make prediction

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

3.1. Fitting a model to data

In [2]:
hd= pd.read_csv("heart-disease.csv")
hd.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
# import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)
X= hd.drop("target", axis= 1)
y= hd["target"]
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2)
clf= RandomForestClassifier()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8524590163934426

calling the fit() method makes ML algorithm to find a connection/patterns between X and y, if there is no y, then it will find patterns only within y

3.2. Making prredictions based ML model

In [4]:
# use trained model to predict
clf.predict(X_test)  # gives labels in the form of y from given data in the form of X

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [5]:
# compare prediction with the true values
y_preds= clf.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [6]:
# another way is to use accuracy_score
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

In [7]:
# predict_proba = gives the probablities of a classification label
# return probabilities rather than labels
clf.predict_proba(X_test[:5]), clf.predict(X_test[:5])

(array([[0.89, 0.11],
        [0.49, 0.51],
        [0.43, 0.57],
        [0.84, 0.16],
        [0.18, 0.82]]),
 array([0, 1, 1, 0, 1], dtype=int64))

In [8]:
# return labels
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

In [9]:
# find the probability of one sample
clf.predict_proba(X_test[:1])

array([[0.89, 0.11]])

In [10]:
# return the label for 1 sample
clf.predict(X_test[:1])

array([0], dtype=int64)

Since the problem is a binary classification, predicting a label with >= 0.5 probability means assingning that label. `predict()` can also be used for regression models.

In [11]:
# importing RandomForestRegressor model
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import fetch_california_housing
housing= fetch_california_housing()
h_df= pd.DataFrame(housing["data"], columns= housing["feature_names"])
h_df["target"]= pd.Series(housing["target"])
#h_df.head()

np.random.seed(42)
X= h_df.drop("target", axis= 1)
y= h_df["target"]
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2)
model= RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8065734772187598

In [12]:
# make predictions
y_preds= model.predict(X_test)

In [13]:
# compare the predictions to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

0.32659871732073664